# Example for the azure-metrics:####/probe/metrics endpoint
---
global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: azure_resourcegraph_examples
    scrape_interval: 1m
    # TODO: Gain a better understanding of what the metrics_path does in Promtheus.
    metrics_path: /metrics
    params: {}
    static_configs:
      - targets: ["host.docker.internal:8080"]