# Example for the azure-metrics:####/probe/metrics endpoint
---
global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: azure_resourcegraph_examples
    scrape_interval: 1m
    # It seems that metrics_path pulls the Azure ResourceGraph metrics from the exporter and makes them available in Prometheus?
    metrics_path: /probe?module=summary
    params: {}
    static_configs:
      - targets: ["host.docker.internal:8080"]